using Distributions, StatsPlots, Statistics
using SimpleMCMC

function MCMC_example()

    # Here are the weights of the students (in kilograms) in a classrom
    # Assuming the weight of the students are generated by a biological
    # process with a normal distribution with mean μ and standard dev σ
    # find the posterior distribution of those two parameters
    data = [ 55.8, 64.1, 61.2, 55.2, 58.0, 69.8, 53.2, 70.0, 63.3, 63.5 ]

    # define our prior for μ as a normal centered on 60 ( required for MCMC )
    mu = Normal(60, 10)
    # define our prior for σ as a exponential with mean of 20 ( required for MCMC )
    sigma = Exponential(20)

    # Put all our parameters into a list
    ListOfParams = Distribution[mu,sigma]

    # The loglikelihood function which returns the log(probability),
    # given a fixed mu and a fixed sigma, of the sequence of datapoints
    function loglikelihood(data::Vector,mu,sigma)
        numofdatapoints = length(data)
        result=0.0
        for k = 1:numofdatapoints
            result += logpdf(Normal(mu,sigma),data[k])
        end
        return result
    end

    p = MetropolisHastings_MCMC(
            data,
            ListOfParams,
            loglikelihood,
            samples=1_000_000,
            burnedinsamples=5000
    )

    # Next we need to display the histogram of the column p[:,1]
    # this is the shape of the posterior produced by MCMC
    vec_mu=vec(p[:,1])  # Convert a Matrix column into a 1-D Vector
    vec_sigma=vec(p[:,2])  # Convert a Matrix column into a 1-D Vector
    describe_paramvec("μ","mu",vec_mu)
    describe_paramvec("sigma","sigma",vec_sigma)
    histogram2d(vec_mu,vec_sigma,nbins=100,xlabel="mu",ylabel="sigma")
end

# We call the main function to kick off the example
MCMC_example()